navi_simによるオブジェクトの前に移動する関数の検証環境を作成した
OUXT-Polaris/robotx_behavior_tree pull request #94
Opened 2024-06-11 13:03 UTC by kentohirogaki

2024-06-23 03:22 UTC, hakuturu583 requested changes

2024-06-23 03:22 UTC, hakuturu583 commented on robotx_behavior_tree/plugins/action/move_to_front_pose_of_object.cpp
> +  std::vector<robotx_behavior_msgs::msg::TaskObject> red_buoys_array_;
指定したオブジェクトの前に移動してほしいというActionなのでこの変数は不要かと思います。

2024-06-23 03:22 UTC, hakuturu583 commented on robotx_behavior_tree/plugins/action/move_to_front_pose_of_object.cpp
> +    }
何色のブイの前に行きたいかは状況次第なので、behavior treeの構造を決めるxmlから指示できるようにしておいてください。

2024-06-23 03:22 UTC, hakuturu583 commented on robotx_behavior_tree/plugins/action/move_to_front_pose_of_object.cpp
> +    }
イメージとしてはこんな感じ

```
<root main_tree_to_execute = "MainTree" >
    <BehaviorTree ID="MainTree">
        <Sequence>
            <Action ID="MoveToFrontPoseOfObject" task_objects="{task_objects}" object_type="red_bouy"/>
        </Sequence>
    </BehaviorTree>
</root>
```

2024-06-23 03:22 UTC, hakuturu583 commented on robotx_behavior_tree/plugins/action/move_to_front_pose_of_object.cpp
> +    }
https://github.com/OUXT-Polaris/robotx_behavior_tree/blob/739c925d4bed7999bec175615ac4f6e64df1323c/robotx_behavior_tree/plugins/action/move_goal_action.cpp#L45-L51

https://github.com/OUXT-Polaris/robotx_behavior_tree/blob/739c925d4bed7999bec175615ac4f6e64df1323c/robotx_behavior_tree/plugins/action/move_goal_action.cpp#L56-L58

こんな感じで書くと、xmlから値を読み込めます。
portの名前はxmlの設定と必ず一致させてください。
事前決めた文字列と異なる文字列が入っていた場合（今回だとred_bouyとかgreen_bouyとかtaskobjectの種類ではない文字列）エラーにしてください。

2024-06-23 03:22 UTC, hakuturu583 commented on robotx_bt_planner/behavior_trees/move_to_front_pose_of_object.xml
> +            <Action ID="MoveToFrontPoseOfObject" task_objects="{task_objects}"/>
portの追加をお願いします！

2024-06-23 03:23 UTC, hakuturu583 commented on robotx_behavior_tree/plugins/action/move_to_front_pose_of_object.cpp
> +  std::vector<robotx_behavior_msgs::msg::TaskObject> red_buoys_array_;
ゴール地点のtask_objectがあれば良いので、

```c++
robotx_behavior_msgs::msg::TaskObject target_object;
```

みたいな型で情報を保存しておくのが望ましいと思います。

2024-11-05 12:56 UTC, kentohirogaki commented
https://github.com/user-attachments/assets/956c2a48-91f3-4e23-a901-8690ad15c276

2024-11-05 12:58 UTC, merged